---
title: "1 Introduction"
output: html_notebook
---


The United Nations recently revised and published new Sustainable Development Goals (SDG’s) for the next 15 years. At least six of the 17 goals are directly linked to water, and several others are indirectly affected by water issues. (The United Nations Department of Economic and Social Affairs, 2016) The sustainable development goals are not separate entities, instead, they are connected to each other in a high degree. This calls for integrated approaches in dealing with the issues the SDG’s attempt to address. Water is central to achieving the goals. In addition, water-related issues have been iden-tified by the World Economic Forum as some of the biggests risks the world is facing in the future (World Economic Forum, 2016).

Access to water and poverty have been linked for a long time in research, and it is un-derstood that water occupies a central role in poverty alleviation. (Sullivan, 2002; Perez-Foguet & Garriga, 2011) Water and poverty are linked through water management, not water scarcity, which is primarily related to food security due to agriculture being the dominant water user globally.  For poverty, water management issues relate to drinking water access, cooking and sanitation through policy failure, lack of infrastructure and low capacity. (Perez-Foguet & Garriga, 2011) These factors have led to development of indicator approaches in water resource research. To answer the need, Water Poverty In-dex (WPI) was developed as holistic tool to assess water resource in an integrated man-ner, combining resource availability, social access to water and the environmental water requirements. (Sullivan, 2002) 

Water Poverty Index has been tested in many case studies on different scales across the world. However, it has only been applied in a single study (to the author’s knowledge) in Mainland Southeast Asia, on Srepok River Basin in Cambodia (Ty, et al., 2010) and in an international comparison (Lawrence, et al., 2002). The Mekong Region is currently undergoing an accelerating dam-building phase, with 72 new large scale dams in the plans or under construction (International Rivers, 2015). Building of the dams is prob-lematic due to its effects on food security, biodiversity and flooding (Ziv, et al., 2011). 

The big challenges faced by the riparian countries of the Mekong in the wake of build-ing the infrastructure provide the motivation for this study. WPI is a useful tool to as-sess a multidimensional issue such as poverty, water and the social and environmental change the new infrastructure causes. The primary goal of this study is to investigate the seasonal and spatial differences of water poverty prior to the accelerated dam building. It is meant as a tool aiding decision making in the work towards the new SDG’s laid out in 2015. In addition, the author thinks of it as a first step in a comprehensive application of WPI in Southeast Asia. A secondary goal of the thesis is to investigate whether the water poverty index could (and should) be extended to include a temporal dimension – water is not only spatially highly varying, but also temporally. Lao People’s Democratic Republic (Laos) is chosen as the area of study for two reasons. First, majority of all the new dam infrastructure is planned and constructed in Laos. Second, the author is famil-iar with the country through other research and having worked in Vientiane for a few months. 





Three research questions guide the investigative process:

1.	Are there distinct differences between areas in their water poverty?
2.	Are there distinct differences in seasonal water poverty?
3.	What are the causes of water poverty in Laos?
a.	Do the causes differ across space and seasons?

The first question seeks to determine spatial distribution of water poverty and whether it is possible to identify areas that are relatively poor in the context of water. The second question seeks to inspect the spatio-temporal dimension of water poverty. Laos is locat-ed in the area with Monsoon rains and it may be expected that differences in water pov-erty can be find across dry and wet seasons. The third question tries to find causes of water poverty, and whether the cause varies in different areas or in different seasons.

To achieve the objectives laid out for this thesis, A Water Poverty Index is developed and calculated for Lao PDR for the dry and wet seasons separately. The indices are then subjected to a number of Exploratory Data Analysis and (Spatial) Data Mining methods to uncover information about the spatial and seasonal water poverty. Global and local exploratory statistical analysis as well as spatial clustering are used to answer the first and second research questions. The third research question is addressed with datamining using Geographically Weighted Principal Component Analysis and Geographically Weighted Regression in addition to spatial clustering.

The analyses in this thesis were done using R version 3.3.0 (R Core Team, 2016), a free and open source statistical programming language. In addition to the analyses, all illus-trations (unless otherwise stated) were created in R using either the base package or “ggplot2”, a package which is based on Leland Wilkinson’s Grammar of Graphics (Wickham, 2009). Since the graphics in this thesis are somewhat complex and detailed, in order to provide a better view, interactive version of the thesis is published in the au-thor’s home page in http://markokallio.fi/waterpoverty/. In addition, the R code and the data are openly published in the home page as well as in GitHub.

This thesis is structured in the following manner: In the second chapter, background information on Laos is given to place the work in its geographical context. In addition, information on current knowledge of the water poverty in Laos as well as general description of Water Poverty Index (WPI), the selected method used in the analyses, is given. The third chapter introduces the theoretical framework on spatial phenomenon, exploratory data analysis and spatial data mining. Following that, the fourth chapter extends the theory into a methodology this thesis follows to build a WPI for Laos and its exploration. The fifth chapter, Results, begins by looking at the selected variables used in WPI calculation, followed by a detailed exploration of WPI across seasons and space. The chapter continues to report the data mining results via spatial clustering, Geographically Weighted Principal Component Analysis and Geographically Weighted Regression. The Sixth chapter discusses the limitations and problems encountered in the research process, and finally, the last chapter concludes the thesis with a summary of the findings and answers to the research questions. 
