---
title: "6 Discussion"
output: html_notebook
---

# 6	Discussion

Water poverty per se has not been studied in Laos in this detail – in fact the only (to the authors knowledge) specifically water poverty-related study that involves Lao PDR is an international comparison by Lawrence et al (2002). The results of this study is on similar lines, with average dry season WPI being comparable to the study by Lawrence et al, with a two notable differences. In this study Access scores were twice as high as in the international study and Use is scored several times higher in the international comparison. This is attributed to the variables used; the components in these two studies measure different things. 

However, despite there is not a large number of studies to compare the results to, some indications can be used. Poverty and water are well known to have deep rooted links (Sullivan, 2002; International Fund for Agricultural Development, 2014; Ward & Kaczan, 2014), and this study found that WPI is low (meaning that water poverty is high) in the mountainous areas – where IFAD (2014) places the poorest population. This study does not include recommendations on how to alleviate water poverty mainly be-cause the one of the main data sources (Population Census) is already more than 10 years old, and it is known that significant improvement has already occurred since the main data sets were collected in 2005 and 2011. Based on the results it seems that measures taken to tackle poverty in general are the exact measures that possibly would address water poverty issues – it was found that the human components of Access, Ca-pacity and Use are the most problematic ones.  

Some significant difficulties were also encountered while exploring water poverty in Laos. This mainly attributed to the high computational requirements of many of the methods employed. Despite running analyses on a relatively powerful PC, some tests and analyses ran for several days or crashing with problems of available memory. These problems mostly manifested in the GWR analyses – Leung’s F3 tests could not be fin-ished due to R crashing after 5 days (more than 120 hours) in on the test. In addition, mixed GWR with a few stationary variables crashed due to memory problems, as did robust GWR for the dry season model. Robust model for the wet season, however, could be finished probably due to fewer significant variables (the result of robust wet season model was worse than basic GWR by R2, AICc and RSS). This may be due to the choice of using R for the analyses – it is known that R may suffer from memory problems when running analyses on large databases. Using alternative environments, e.g. Python, may have had resolved this issue, however it could not be done under the time limit for this study.

The third research question about the causes of water poverty is answered thoroughly in this study, however, the causes found in this study are not explicitly proven in this the-sis. More precisely, it has been shown that the human components are the most im-portant. Links between poverty (e.g. Sullivan  (2002), Ward and Kaczan (2014) among many others) economic growth and jobs (UNESCO, 2016) and water has been shown in many studies. In practise, poverty as a multidimensional phenomenon is directly linked to all of the human components – Access, Capacity and Use. Despite this general knowledge, the reader should note that the causes presented are actually correlations that have been found by different techniques and assumed as the causes in the light of knowledge from literature.

The following two sub-sections deal with the weaknesses and strengths identified with the chosen methodology. 


## 6.1	Weaknesses
The major potential weakness with this study relates to the tool of assessment – WPI – and how it is employed here. WPI is a relative index – traditionally (most of) the chosen variables are standardized through minimum and maximum of the sample used. This makes it very difficult to compare results with other studies – unless the variables and their ranges are comparable. This can be addressed e.g. by setting standard upper and lower limits for variables, as was done in this study for some variables. However, not all variables were standardized in this way. In addition, the variables used for the compo-nents are slightly different in this study than what are normally used to calculate WPI. I used Access to measure presence of water infrastructure – normally it includes variables that measure penetration of safe water and sanitation in the communities. In addition, Use is generally standardized to the available water resource – I used it without this standardization. 

When it comes to research on WPI itself, Fenwick (2010) concluded in her doctoral dis-sertation that in addition to scale (Sullivan, et al., 2006), entirely different geographical areas may require different indicators to capture the water poverty situation. In the course of this research, it was found that the seasonal water poverty is very different in a same way as a rural and urban area are different to each other. It should be considered whether selecting different indicators for dry and wet season should be done when ap-plying WPI in areas with stark seasonal differences. 

Another major issue when developing WPI for this particular study was data. Unfortu-nately, many aspects of the environment could not be taken into account in a satisfacto-ry matter and therefore they were dropped out. Water quality data is available only in a handful of data points. To use them meaningfully, they would have needed to be aggre-gated to very large areas which would have not made sense, as the aim was to calculate village-level WPI. In addition, no reliable data about existing dams were found to have them included in the water resource modelling. However, water scarcity occurs in a lim-ited area in Xayabouly and Vientiane Provinces, and the main impact on component scores would have occurred here – if at all.  Final major disadvantage of the variable choices is in using road access alone to measure the access to the villages. In reality, riv-ers are often used as pathways in areas which road network does not cover – this dimen-sion of transport is not included in this study. River access could have a large impact in the Capacity component scores.

Another weakness is that, despite the dataset having a high coverage of all villages in Laos, there are areas where no villages are included. The reason of their exclusion was that they were not represented in either Population or Agricultural Censuses. Had there been data, some province level conclusions would have likely been different. Primarily this would have influenced Bolikhamxai, which was found to be the least water-poor province of all. However, all of the mountainous villages in this province were dropped from the final dataset – had they been present, the final numbers would have dropped considerably. 

Finally, Fenwick (2010), along with a number of other researches, argue that, at commu-nity level, the local population should be included in the selection of variables relevant to their perception of water poverty. This unfortunately could not be done for this the-sis. The work is entirely depending on datasets that are openly available, which however were not collected specifically for the needs of water poverty research.

## 6.2	Strengths
In addition to weaknesses, this study does have some distinct strengths. To my knowledge, this is the first study that explicitly applied WPI to dry and wet seasons. Their differences are often mentioned in literature, but there is a lack of studies which compare the impacts of season to water-related socio-economic indicators. This study found that there are significant differences present in other components than just actual physical water availability. 

WPI is a composite index and as such, suffers from the disadvantages of composite in-dices. One of the drawbacks is that often the components strongly correlate with them-selves, reducing their usefulness. However, in this study none of the components show strong correlation, and only one (Access and Capacity) correlate with a medium strength. This is advantageous since it means that each component measures a different water poverty linked phenomenon. 

In addition, some weaknesses described by Fenwick (2010) in her doctoral dissertation are evaded in this study. It has been found in many studies that components correlate despite carefully selecting indicators, and often it is argued whether a component is a useful addition or not. As mentioned, the components do not correlate to a high degree, and this is therefore interpreted as one of the strengths of this study. In addition, a prob-lem often raised in literature is weighting (e.g. Molle and Mollinga (2003) and Garriga and Foguet (2010)) being a political choice. It is countered here by using statistical methods for ”objective” weighting. However, Fenwick (2010) argues that since WPI is intended as a policy tool, purely statistical weighting may not result in an optimum from policy maker’s point of view. Additionally, it is argued in many papers that one should not concentrate on WPI, but direct analysis on the components – which is what was mainly done in this research.

Finally, the data and R code used for analysis are opened for anyone to check and repli-cate. This increases the transparency of the study, something that is unnecessarily often lacking in research, and allows for easy modification of the analysis if one deems it nec-essary. 
