---
title: "7 Conclusion"
output: html_notebook
---

# 7	Conclusion

This study started with an aim to investigate water poverty in Lao PDR in a time before the current, very fast dam building commenced in the country. The primary goal was to establish the spatial and seasonal differences of water poverty using WPI, and to pro-vide useful information to the work fulfilling the new Sustainable Development Goals introduced in 2015. Secondarily, the usefulness of inclusion a temporal (or more precise-ly, seasonal) dimension to WPI has been addressed (although, not explicitly reported in this paper). The actual study followed three key research questions: 

1.	Are there distinct differences between areas in their water poverty?
2.	Are there distinct spatio-temporal differences in water poverty?
3.	What are the causes of water poverty in Laos? Do the causes differ across space and seasons?

A meaningful answer to all of the research questions was found during the research pro-ject. The following sections concludes the answer for each of these questions.

## 7.1	Spatial Variation in Water Poverty
The spatial variation in water poverty was explored in three levels: The variables that make out the components, the components individually, and finally the WPI itself. Sig-nificant spatial variation was found in all three levels: The smallest Moran’s Index value was found to be 0.28, which is commonly considered as a strong spatial relationship, while the highest value was more than 0.9 – variable nearly entirely determined by loca-tion. While the variables and components spatially autocorrelate, however, they show very little correlation with each other. There seem to be different spatial processes that drive each of the components. However, correlation can be found when the components are compared against the final index value: Use component strongly correlates with WPI (correlation coefficient of 0.64-0.67) in both of the seasons. It appears that a higher live-lihood dependency on water can predict a high portion of the overall water poverty. This is especially surprising, since the Use component scores are low accompanied with low weight in the used PCA-derived weighting scheme. Additionally, Use component does not correlate with any other component. Relevant to the first research question, the correlations vary across the country from locally weak to locally strong correlations.

WPI was also analysed through provinces, and it was found that there are statistically significant differences in the water poverty in different provinces. Three groups of prov-inces were identified: Water-Poor (Xekong, Oudomxai, Phongsaly and to a lower de-gree Louangnamtha and Houaphan), Average, and Water-Rich (Vientiane Capital, Vien-tiane and Bolikhamxai). In fact, cluster analysis revealed that Laos can be divided into two main groups: the water-poor and the water-rich.

As a conclusion, there is a large amount of evidence to support a claim that there are distinct differences between regions in their water poverty. This includes both, evidence from visual exploration as well as statistical analysis. 


## 7.2	Spatio-Temporal Variation in Water Poverty
Spatio-temporal dimension of water poverty was analysed through WPI calculated for the dry and wet season. All components, except Access, included variables that change between the seasons. WPI was found to change, with fairly small differences in other WPI components except Resources, which doubles its value in when season changes from dry to wet. This dramatic increase in Resources also results in a significant increase in the overall WPI value. However, despite small differences, visual examination of component maps reveal that spatial changes do occur. In addition, in some areas, the change between dry and wet WPI is dramatic; increase in the index value can be as high as 40 index points (from a maximum value of 100).  

Changing component and WPI values were not the only evidence found in the study. Correlations between the components and WPI also change according to seasons. Dry season WPI correlates (correlation coefficient >0.30) with RES, CAP and USE while wet season correlates with CAP, USE and ENV.  In addition, weighting scheme de-rived from PCA result in significantly different schemes; wet season weights emphasize the human components (ACC, CAP, USE) while dry season emphasize the environment components (RES, ENV). Additionally, the clusters found to be either water-poor or water-rich slightly change between seasons, with a higher share of villages assigned to a rich cluster in the wet season than in the dry season. Finally, the relative rank among the provinces changes between the seasons. Some provinces improve dramatically their rela-tive as well as absolute water poverty as wet season starts. A small number of villages, however, behave in the opposite way with wet season WPI proving to be lower than dry season WPI. 

The visual and statistical evidence clearly supports the conclusion that there are signifi-cant spatio-temporal differences in the water poverty across the two seasons. 


## 7.3	Causes of Water Poverty
The causes of water poverty vary somewhat according to the explorative and data min-ing method employed. As a generalization, it can be said that most of the water-related problems in Laos are in the human components – Access, Capacity and Use – with some spatial differences. Clustering analysis reveals that the biggest difference between wa-ter-rich and water-poor is in the Capacity component, and that the clusters correlate with road access to a very high degree.  In addition, Environment scores higher in the rich clusters than in the poorer ones. Capacity, as a component, is a common theme across the analyses. It has a large range, spanning near the entire range of Index, and proving to correlate with WPI. In GWPCA, Capacity is the most loaded component in the first PC on both season. Finally, in GWR, variables that make Capacity are all among the 11 first picked by the step-wise model selection algorithm. Therefore, it is concluded that Ca-pacity is the single most important component driving water poverty in Laos. 

However, the picture is not as simple as singling Capacity out as the cause. The other human components (Access, Use) are important throughout the country, and in the dry season, Resources is a significant driver in the northwest of the country. Especially Use is an important indicator, as it correlates strongly with dry and wet season water poverty despite scoring low and having a low weight.  This is despite Use being the lowest scor-ing component. In fact, in absolute terms, water poverty could be addressed by improv-ing the infrastructure and with more efficient use of water.

According to GWPCA, share population that depends on agri- or aquaculture (belong-ing to Use component) as the main source of their income is the most important variable in the dry season, and second most important in the wet season. Road access (Capacity component) is the most loaded variable in the wet season, and an important variable in the dry season as well. In addition, surface water availability (Resources) and the travel time to capitals (Capacity) are significant predictors in the dry season. Toilet type (Ac-cess) is the most loaded in the third PC in the wet season. A similar picture is painted by GWR models. The most important predictors are shared by the seasons; they are mostly from Capacity component (all four are included in the top 11 predictors from both sea-sons), Use (all three included), precipitation from the Resources component and soil degradation from ENV. The rest of the components are largely the same, however, an important difference is that dry season predictors include more environmental and infra-structure variables. The causes of water poverty, however, were not completely discov-ered as is evident from the low R2 of the GWR model in the northwest and around the capital city.

The answer to the last research question is therefore that Capacity and other human components are important (in relative terms) everywhere in Laos with Resources being a major factor in the northwest during dry season. Use and Access are the least scoring, and biggest absolute improvements can be found in these two components. Dependence on agriculture and road access are the two most important predictors of water-related poverty, suggesting that rural population is more vulnerable. Additionally, it was found that significant spatial variation in variables correlating with WPI.

## 7.4	The Way Forward
This study created a foundation for exploring water poverty further in Laos (and in Southeast Asia). It has also highlighted additional research questions that need to be answered in order to create a comprehensive picture in the dimensions that cause and drive water poverty. 

The study showed that the causes of water poverty change according to space and re-gion. WPI is reliant on geospatial data (Sullivan, 2002) and thus does take the spatial dimension in to account. However, conventionally seasonal variability is only taken into account in Resources component as a variable that describes the seasonal changes of the resource. This study has made it clear that, at least in a highly seasonal environment, single index is not enough to describe the differences between seasons. This is due to the nature of chosen variables which are changing according to season. WPI aims to be a holistic tool (Sullivan, 2002) to assess the complex phenomenon of water-related pov-erty. Further research is therefore needed whether the difference between seasons war-rants development of WPI in a direction that better represents the changing drivers across seasons. 

In addition, continued assessment of water poverty is needed to describe the current situation in the Mekong – this study was based on data mainly collected prior the accel-erated building of large scale water infrastructure. It is likely that the dam building cur-rently occurring in Laos changes the picture painted by WPI. A follow-up study using more recent data (e.g. Population Census conducted in 2015, which was unavailable at the time of this research) should therefore be done to support impact assessments on the infrastructure projects and to better direct efforts to achieve SDG’s laid out by the United Nations. It is also known that significant improvement in poverty has occurred since the data collection for the 2005 Population Census (World Bank Group, 2016; Coulombe, et al., 2016). 
